# Generated by Django 5.0.3 on 2024-03-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание фото"
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Фото",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название тега"),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Красный"),
                            ("blue", "Синий"),
                            ("green", "Зеленый"),
                            ("yellow", "Желтый"),
                            ("orange", "Оранжевый"),
                            ("purple", "Фиолетовый"),
                            ("pink", "Розовый"),
                            ("brown", "Коричневый"),
                            ("gray", "Серый"),
                            ("black", "Черный"),
                            ("white", "Белый"),
                        ],
                        default="gray",
                        max_length=10,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, verbose_name="Уникальный слаг"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
